Repository hanghae99-MEALCHAK/MEALCHAK-server-application, pull requests merged in 2021-07, with the labels that each got.

#4 UserController 수정
  src/main/java/com/mealchak/mealchakserverapplication/controller/UserController.java
  src/main/java/com/mealchak/mealchakserverapplication/dto/UserInfoDto.java
  src/main/java/com/mealchak/mealchakserverapplication/dto/response/HeaderDto.java
  src/main/java/com/mealchak/mealchakserverapplication/dto/response/UserInfoDto.java
  src/main/java/com/mealchak/mealchakserverapplication/jwt/JwtTokenProvider.java
  src/main/java/com/mealchak/mealchakserverapplication/oauth2/KakaoOAuth2.java
  src/main/java/com/mealchak/mealchakserverapplication/oauth2/UserDetailsServiceImpl.java
  src/main/java/com/mealchak/mealchakserverapplication/service/UserService.java
Labels: Tbread

#5 모집글 검색기능추가
  src/main/java/com/mealchak/mealchakserverapplication/controller/PostController.java
  src/main/java/com/mealchak/mealchakserverapplication/model/Post.java
  src/main/java/com/mealchak/mealchakserverapplication/model/User.java
  src/main/java/com/mealchak/mealchakserverapplication/repository/PostRepository.java
  src/main/java/com/mealchak/mealchakserverapplication/service/PostService.java
Labels: eungsoo

#6 검색기능 오류 수정
  src/main/java/com/mealchak/mealchakserverapplication/controller/PostController.java
  src/main/java/com/mealchak/mealchakserverapplication/service/PostService.java
Labels: bug, eungsoo

#7 카카오 로그인 에러 fix, 모집글 : 레스토랑 항목 추가
  src/main/java/com/mealchak/mealchakserverapplication/controller/PostController.java
  src/main/java/com/mealchak/mealchakserverapplication/controller/UserController.java
  src/main/java/com/mealchak/mealchakserverapplication/dto/request/PostRequestDto.java
  src/main/java/com/mealchak/mealchakserverapplication/dto/response/UserInfoDto.java
  src/main/java/com/mealchak/mealchakserverapplication/jwt/JwtTokenProvider.java
  src/main/java/com/mealchak/mealchakserverapplication/model/Post.java
  src/main/java/com/mealchak/mealchakserverapplication/model/User.java
  src/main/java/com/mealchak/mealchakserverapplication/repository/PostRepository.java
  src/main/java/com/mealchak/mealchakserverapplication/service/PostService.java
  src/main/java/com/mealchak/mealchakserverapplication/service/UserService.java
  src/main/resources/static/login.html
Labels: error fixed, eungsoo
